spring.application.name=bursary-notification-service
server.port=8083
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=489
spring.mail.username=stanleigh3oduor@gmail.com
spring.mail.password=bamv ljqh giuv cusb 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true


#Enable MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bursary_notification_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA (Hibernate) Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

infobip.api.url=https://kqvxw3.api.infobip.com/sms/2/text/advanced
infobip.api.key=65cc2c6b813e5da2733f62d512687197-defcfce0-d67e-4daa-b5fd-c28335dc9f9b
